const {harness,base,product,recipe,activity,assert,fs,wait,text}=require('./harness.cjs');
const results=[];let serial=0;
async function test(area,name,fn,opts={}){const h=harness(opts);try{await wait();const evidence=await fn(h);results.push({id:'D'+String(++serial).padStart(3,'0'),area,name,status:'PASS',evidence:evidence||null,errors:h.errors});}catch(e){results.push({id:'D'+String(++serial).padStart(3,'0'),area,name,status:'FAIL',evidence:e.message,dom:h.dump(),errors:h.errors});}finally{h.close()}}
const stockData=(p=product())=>{const b=base();b.products=[p];b.productArchive={[p.id]:p};return b;};
const ok=(r)=>assert.equal(r,null);const reject=(h,fn,...args)=>{const before=h.raw(),r=h.call(fn,...args);assert.equal(typeof r,'string');assert.equal(h.raw(),before,'Rejected transaction mutated persisted data');return r};
(async()=>{
 // Validation and transactions: public store functions run against isolated account.
 await test('Inventori','Tambah stok normal',h=>{ok(h.call('Le','qa',product()));assert.equal(h.data().products[0].quantity,10);});
 for(const qty of [0,-1,0.00001,1.00001,1e309])await test('Inventori','Tolak jumlah '+qty,h=>reject(h,'Le','qa',product('p1','egg',qty)));
 await test('Inventori','Konversi 1.5kg ke gram',h=>{ok(h.call('Le','qa',product('rice1','rice',1.5,{unit:'kg'})));assert.equal(h.data().products[0].quantity,1500);});
 await test('Inventori','Konversi 2 botol ×250ml',h=>{ok(h.call('Le','qa',product('milk1','milk',2,{unit:'botol'})));assert.equal(h.data().products[0].quantity,500);});
 await test('Inventori','Tolak satuan tidak sesuai',h=>reject(h,'Le','qa',product('p1','egg',1,{unit:'kg'})));
 for(const date of ['2026-02-30','2026-13-01','not-date'])await test('Inventori','Tolak expiry '+date,h=>reject(h,'Le','qa',product('p1','egg',1,{expiryDate:date})));
 await test('Inventori','Tanggal stok masa depan ditolak',h=>reject(h,'Le','qa',product('p1','egg',1,{receivedDate:'2026-10-08'})));
 await test('Inventori','Tanggal stok lampau diperbolehkan',h=>{ok(h.call('Le','qa',product('p1','egg',1,{receivedDate:'2026-10-06'})));});
 await test('Inventori','Stok tanpa tanggal tetap dicatat',h=>{ok(h.call('Le','qa',product('p1','egg',1,{expiryKind:'unknown',expiryDate:''})));assert.equal(h.data().products.length,1);});
 await test('Inventori','Edit metadata tidak mengubah jumlah',h=>{const p={...h.data().products[0],location:'Rak',expiryDate:'2026-10-20'};ok(h.call('Re','qa',p));assert.equal(h.data().products[0].quantity,10);assert.equal(h.data().products[0].location,'Rak');},{data:stockData()});
 await test('Inventori','Edit langsung jumlah ditolak atomik',h=>reject(h,'Re','qa',{...h.data().products[0],quantity:12}),{data:stockData()});
 await test('Inventori','Hapus batch manual tanpa riwayat',h=>{ok(h.call('Ue','qa','p1',h.data().products[0]));assert.equal(h.data().products.length,0);},{data:stockData()});
 await test('Inventori','Hapus batch pernah dipakai diblokir',h=>{ok(h.call('nt','qa',activity()));return reject(h,'Ue','qa','p1');},{data:stockData()});
 await test('Inventori','Koreksi stok 10→7, ledger konsisten',h=>{ok(h.call('Ge','qa','p1',7,'Hasil hitung'));assert.equal(h.data().products[0].quantity,7);assert(h.call('He','qa','p1').summary.consistent);},{data:stockData()});
 await test('Inventori','Koreksi nol, batch arsip, batalkan memulihkan',h=>{ok(h.call('Ge','qa','p1',0,'Hitung habis'));const id=h.data().activityLog[0].id;assert.equal(h.data().products.length,0);ok(h.call('Je','qa',id));assert.equal(h.data().products[0].quantity,10);assert(h.call('He','qa','p1').summary.consistent);},{data:stockData()});
 await test('Inventori','Koreksi sama/negatif/alasan kosong ditolak',h=>{for(const [n,s]of [[10,'Hitung'],[-1,'Hitung'],[7,'']])reject(h,'Ge','qa','p1',n,s);},{data:stockData()});
 await test('Inventori','Batalkan koreksi yang sudah ada aktivitas lebih baru diblokir',h=>{ok(h.call('Ge','qa','p1',7,'Hitung'));const id=h.data().activityLog[0].id;ok(h.call('nt','qa',activity('a1',2,{createdAt:'2026-10-07T06:00:00Z'})));return reject(h,'Je','qa',id);},{data:stockData()});
 // Activities.
 await test('Aktivitas','Pemakaian 2, edit jadi3, hapus mengembalikan10',h=>{const a=activity();ok(h.call('nt','qa',a));assert.equal(h.data().products[0].quantity,8);ok(h.call('et','qa',{...a,items:[{...a.items[0],quantity:3}]}));assert.equal(h.data().products[0].quantity,7);ok(h.call('tt','qa',a.id));assert.equal(h.data().products[0].quantity,10);assert(h.call('He','qa','p1').summary.consistent);},{data:stockData()});
 await test('Aktivitas','Pemakaian habis dan hapus memulihkan batch lengkap',h=>{ok(h.call('nt','qa',activity('a1',10)));assert.equal(h.data().products.length,0);ok(h.call('tt','qa','a1'));assert.equal(h.data().products[0].expiryDate,'2026-10-14');assert.equal(h.data().products[0].quantity,10);},{data:stockData()});
 await test('Aktivitas','Jumlah melebihi stok ditolak atomik',h=>reject(h,'nt','qa',activity('a1',11)),{data:stockData()});
 await test('Aktivitas','Tanggal aktivitas masa depan ditolak',h=>reject(h,'nt','qa',activity('a1',2,{date:'2026-10-08'})),{data:stockData()});
 await test('Aktivitas','Pemakaian sebelum stok tersedia ditolak',h=>reject(h,'nt','qa',activity('a1',2,{date:'2026-09-30'})),{data:stockData()});
 await test('Aktivitas','Pemakaian batch lewat tanggal ditolak',h=>reject(h,'nt','qa',activity()),{data:stockData(product('p1','egg',10,{expiryDate:'2026-10-06'}))});
 await test('Aktivitas','Pembuangan batch lewat tanggal boleh; hapus memulihkan',h=>{ok(h.call('nt','qa',activity('a1',2,{action:'disposed'})));assert.equal(h.data().products[0].quantity,8);ok(h.call('tt','qa','a1'));assert.equal(h.data().products[0].quantity,10);},{data:stockData(product('p1','egg',10,{expiryDate:'2026-10-06'}))});
 await test('Aktivitas','ID aktivitas sama tidak mengurangi dua kali',h=>{ok(h.call('nt','qa',activity()));ok(h.call('nt','qa',activity()));assert.equal(h.data().products[0].quantity,8);assert.equal(h.data().activityLog.length,1);},{data:stockData()});
 await test('Aktivitas','Duplikat batch dalam satu aktivitas dihitung total',h=>{const a=activity();a.items.push({...a.items[0]});ok(h.call('nt','qa',a));assert.equal(h.data().products[0].quantity,6);},{data:stockData()});
 await test('Aktivitas','Transaksi multibahan gagal tidak mengubah bahan pertama',h=>{const a=activity();a.items.push({productId:'missing',quantity:1,unit:'buah'});return reject(h,'nt','qa',a);},{data:stockData()});
 await test('Aktivitas','Hapus pemakaian sebelum hitung ulang memerlukan konfirmasi fisik',h=>{ok(h.call('nt','qa',activity('a1',2,{createdAt:'2026-10-07T04:00:00Z'})));ok(h.call('Ge','qa','p1',6,'Hitung'));const msg=reject(h,'tt','qa','a1');assert.match(msg,/Konfirmasi/);const conflicts=h.call('Ae','qa',h.data().activityLog.find(a=>a.id==='a1'));ok(h.call('tt','qa','a1',[],conflicts.map(c=>({productId:c.product.id,expectedQuantity:c.product.quantity,adjustmentId:c.adjustmentId,quantity:6}))));assert.equal(h.data().products[0].quantity,6);assert(h.call('He','qa','p1').summary.consistent);},{data:stockData()});
 // Recipes.
 await test('Resep','Membuat resep tidak mengurangi stok',h=>{ok(h.call('at','qa',recipe()));assert.equal(h.data().products[0].quantity,10);},{data:stockData()});
 await test('Resep','Duplikat bahan ditolak atomik',h=>{const r=recipe();r.ingredients.push({...r.ingredients[0],id:'other'});return reject(h,'at','qa',r);});
 for(const portions of [0,1.5,101])await test('Resep','Porsi '+portions+' ditolak',h=>reject(h,'at','qa',recipe('r1','egg',2,{servings:portions})));
 await test('Resep','Masak 3porsi memakai6',h=>{ok(h.call('st','qa','r1',3));assert.equal(h.data().products[0].quantity,4);assert.equal(h.data().activityLog[0].servings,3);},{data:{...stockData(),recipes:[recipe()]}});
 await test('Resep','Stok kurang diblokir atomik',h=>reject(h,'st','qa','r1',6),{data:{...stockData(),recipes:[recipe()]}});
 await test('Resep','FEFO: batch tanggal terdekat dipakai dahulu',h=>{ok(h.call('st','qa','r1',1));assert.equal(h.data().productArchive.p1.quantity,0);assert.equal(h.data().products.find(p=>p.id==='p2').quantity,9);},{data:{...base(),products:[product('p2','egg',10,{expiryDate:'2026-10-20'}),product('p1','egg',1,{expiryDate:'2026-10-08'})],recipes:[recipe()]}});
 await test('Resep','Batch lewat tanggal tidak dihitung siap',h=>{assert.equal(h.call('I',recipe(),h.data().products,1,h.data().itemMasters)[0].available,0);return reject(h,'st','qa','r1',1);},{data:{...stockData(product('p1','egg',10,{expiryDate:'2026-10-06'})),recipes:[recipe()]}});
 await test('Resep','Batch tanpa tanggal perlu verifikasi; setelah diperiksa bisa dipakai',h=>{assert.equal(h.call('I',recipe(),h.data().products,1,h.data().itemMasters)[0].unverified,10);reject(h,'st','qa','r1',1);ok(h.call('st','qa','r1',1,undefined,['p1']));assert.equal(h.data().products[0].quantity,8);},{data:{...stockData(product('p1','egg',10,{expiryDate:'',expiryKind:'unknown'})),recipes:[recipe()]}});
 await test('Resep','Ubah pemakaian saat stok cukup (2→1) mengurangi sesuai aktual',h=>{ok(h.call('st','qa','r1',1,[{ingredientId:'ing_r1',quantity:1}]));assert.equal(h.data().products[0].quantity,9);assert.equal(h.data().recipes[0].ingredients[0].quantity,2);},{data:{...stockData(),recipes:[recipe()]}});
 await test('Resep','Ubah pemakaian saat nominal kurang tetapi aktual cukup (stok1/resep2/aktual1)',h=>{ok(h.call('st','qa','r1',1,[{ingredientId:'ing_r1',quantity:1}]));assert.equal(h.data().products.length,0);},{data:{...stockData(product('p1','egg',1)),recipes:[recipe()]}});
 await test('Resep','Hapus resep menjaga riwayat masak',h=>{ok(h.call('st','qa','r1',1));ok(h.call('ot','qa','r1'));assert.equal(h.data().recipes.length,0);assert.equal(h.data().activityLog.length,1);},{data:{...stockData(),recipes:[recipe()]}});
 await test('Resep','Konversi bahan 0.5liter memakai500ml',h=>{ok(h.call('st','qa','r1',1));assert.equal(h.data().products[0].quantity,250);},{data:{...stockData(product('p1','milk',750)),recipes:[recipe('r1','milk',0.5,{ingredients:[{id:'ing_r1',itemId:'milk',name:'Susu',category:'Segar',quantity:0.5,unit:'liter'}]})]}});
 // Shopping.
 await test('Belanja','Buat rencana tidak menambah stok',h=>{const r=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:5}]);assert.equal(r.error,null);assert.equal(h.data().products.length,0);assert.equal(h.data().shoppingItems.length,1);});
 await test('Belanja','Rencana duplikat bahan ditolak atomik',h=>{const before=h.raw(),r=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2},{itemId:'egg',quantity:2}]);assert.equal(typeof r.error,'string');assert.equal(h.raw(),before);});
 await test('Belanja','Pembelian sebagian, dua batch, selesai',h=>{const a=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:5}]);const i=h.data().shoppingItems[0];ok(h.call('vt','qa',i.id,product('x','egg',2)));assert.equal(h.data().shoppingItems[0].bought,false);reject(h,'ht','qa',a.id);ok(h.call('vt','qa',i.id,product('x','egg',3)));assert.equal(h.data().products.length,2);ok(h.call('ht','qa',a.id));assert(h.data().shoppingActivities[0].completedAt);});
 await test('Belanja','Beli lebih dari rencana dicatat aktual',h=>{h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2}]);ok(h.call('vt','qa',h.data().shoppingItems[0].id,product('x','egg',3)));assert.equal(h.data().products[0].quantity,3);assert(h.data().shoppingItems[0].bought);});
 await test('Belanja','Pembelian item salah ditolak',h=>{h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2}]);return reject(h,'vt','qa',h.data().shoppingItems[0].id,product('x','rice',3));});
 await test('Belanja','Batalkan pembelian belum dipakai menghapus batch dan membuka selesai',h=>{const a=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2}]);let i=h.data().shoppingItems[0];ok(h.call('vt','qa',i.id,product('x','egg',2)));ok(h.call('ht','qa',a.id));ok(h.call('St','qa',i.id));assert.equal(h.data().products.length,0);assert.equal(h.data().shoppingItems[0].bought,false);assert.equal(h.data().shoppingActivities[0].completedAt,undefined);});
 await test('Belanja','Batalkan pembelian sudah dipakai diblokir',h=>{h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:5}]);const i=h.data().shoppingItems[0];ok(h.call('vt','qa',i.id,product('x','egg',5)));const p=h.data().products[0];ok(h.call('nt','qa',activity('a1',2,{items:[{productId:p.id,quantity:2,unit:'buah'}]})));return reject(h,'St','qa',i.id);});
 await test('Belanja','Edit pembelian setelah dipakai menjaga ledger; kurang dari keluar ditolak',h=>{h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:5}]);const i=h.data().shoppingItems[0];ok(h.call('vt','qa',i.id,product('x','egg',5)));const p=h.data().products[0];ok(h.call('nt','qa',activity('a1',2,{items:[{productId:p.id,quantity:2,unit:'buah'}]})));reject(h,'xt','qa',i.id,p.id,1);ok(h.call('xt','qa',i.id,p.id,4));assert.equal(h.data().products[0].quantity,2);assert(h.call('He','qa',p.id).summary.consistent);assert.equal(h.data().shoppingItems[0].bought,false);});
 await test('Belanja','Edit rencana dibawah yang diterima ditolak',h=>{h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:5}]);const i=h.data().shoppingItems[0];ok(h.call('vt','qa',i.id,product('x','egg',3)));return reject(h,'_t','qa',i.id,{...i,quantity:2});});
 await test('Belanja','Menghapus item dengan pembelian belum dipakai menghapus stok',h=>{h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:5}]);const i=h.data().shoppingItems[0];ok(h.call('vt','qa',i.id,product('x','egg',5)));ok(h.call('Tt','qa',i.id));assert.equal(h.data().shoppingItems.length,0);assert.equal(h.data().products.length,0);});
 await test('Belanja','Menghapus aktivitas yang sudah menerima stok diblokir',h=>{const a=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:5}]);ok(h.call('vt','qa',h.data().shoppingItems[0].id,product('x','egg',3)));return reject(h,'mt','qa',a.id);});
 await test('Belanja','Rencana gabungan dua resep tidak menghitung stok dua kali',h=>{ok(h.call('ut','qa','r1',1,undefined,'Meal prep'));const id=h.data().shoppingActivities[0].id;assert.equal(h.data().shoppingItems[0].quantity,1);ok(h.call('ut','qa','r2',1,id));assert.equal(h.data().shoppingItems[0].quantity,3);},{data:{...stockData(product('p1','egg',1)),recipes:[recipe('r1'),recipe('r2')]}});
 await test('Belanja','Rencana resep sama disimpan ulang tidak menggandakan',h=>{ok(h.call('ut','qa','r1',1,undefined,'Meal prep'));const id=h.data().shoppingActivities[0].id;ok(h.call('ut','qa','r1',1,id));assert.equal(h.data().shoppingItems[0].quantity,1);},{data:{...stockData(product('p1','egg',1)),recipes:[recipe()]}});
 await test('Belanja','Rencana resep dikurangi mempertahankan daftar dan memberi potensi overbuy',h=>{ok(h.call('ut','qa','r1',3,undefined,'Meal prep'));const id=h.data().shoppingActivities[0].id;ok(h.call('ut','qa','r1',1,id));assert.equal(h.data().shoppingItems[0].quantity,5);return {plannedNeed:h.data().shoppingActivities[0].recipePlans[0].ingredients[0].quantity,shoppingQuantity:5,note:'Design behavior: no automatic reduction'};},{data:{...stockData(product('p1','egg',1)),recipes:[recipe()]}});
 // Master dependencies.
 await test('Master','Tambah master baru & nama duplikat beda huruf diblokir',h=>{ok(h.call('de','qa',{name:'Kopi',category:'Pokok',unit:'gram'}));return reject(h,'de','qa',{name:'  KOPI  ',category:'Pokok',unit:'kg'});});
 await test('Master','Ubah satuan dasar item terpakai diblokir',h=>reject(h,'de','qa',{...h.data().itemMasters[0],unit:'pcs'},'egg'),{data:stockData()});
 await test('Master','Arsip item dengan stok/resep diblokir',h=>reject(h,'fe','qa','egg',false),{data:stockData()});
 await test('Master','Arsip master tanpa penggunaan dan aktifkan kembali',h=>{ok(h.call('fe','qa','egg',false));assert(!h.data().itemMasters[0].active);ok(h.call('fe','qa','egg',true));assert(h.data().itemMasters[0].active);});
 await test('Master','Isi kemasan terpakai tidak dapat diubah',h=>reject(h,'de','qa',{...h.data().itemMasters[2],packageSize:500},'milk'),{data:stockData(product('p1','milk',500))});
 await test('Master','Kategori duplikat beda huruf ditolak',h=>reject(h,'ye','qa','category','  POKOK  '));
 await test('Master','Rename kategori memindah stok, master, resep',h=>{ok(h.call('be','qa','category','Segar','Segar Baru'));assert.equal(h.data().products[0].category,'Segar Baru');assert.equal(h.data().recipes[0].ingredients[0].category,'Segar Baru');assert.equal(h.data().itemMasters[0].category,'Segar Baru');},{data:{...stockData(),recipes:[recipe()]}});
 await test('Master','Hapus kategori terpakai tanpa tujuan ditolak; pindah aman',h=>{reject(h,'xe','qa','category','Segar');ok(h.call('xe','qa','category','Segar','Pokok'));assert.equal(h.data().products[0].category,'Pokok');assert(!h.data().categories.includes('Segar'));},{data:stockData()});
 await test('Master','Hapus lokasi terpakai boleh menjadi tanpa lokasi',h=>{ok(h.call('xe','qa','location','Kulkas'));assert.equal(h.data().products[0].location,undefined);},{data:stockData(product('p1','egg',10,{location:'Kulkas'}))});
 // Auth and persistence.
 await test('Akun','Login password salah tidak mengubah sesi',h=>{h.w.localStorage.removeItem('dapur_session');assert.equal(h.call('ne','qa','wrong'),'Password salah.');assert.equal(h.w.localStorage.getItem('dapur_session'),null);ok(h.call('ne','qa','audit-only'));assert.equal(h.w.localStorage.getItem('dapur_session'),'qa');});
 await test('Akun','Ubah password memerlukan password lama, baru dapat login',h=>{assert.equal(typeof h.call('te','qa','wrong','new'),'string');ok(h.call('te','qa','audit-only','new'));assert.equal(h.call('ne','qa','audit-only'),'Password salah.');ok(h.call('ne','qa','new'));});
 await test('Akun','Logout menghapus sesi tetapi mempertahankan data',h=>{const before=h.raw();h.call('re');assert.equal(h.w.localStorage.getItem('dapur_session'),null);assert.equal(h.raw(),before);});
 await test('Akun','Data akun kedua terisolasi di perangkat sama',h=>{ok(h.call('H','qa2','audit-only'));h.call('oe','qa2',base());ok(h.call('Le','qa2',product()));assert.equal(h.data().products.length,0);assert.equal(h.call('ae','qa2').products.length,1);});
 await test('Akun','Password tidak disimpan sebagai teks asli',h=>{assert.notEqual(JSON.parse(h.raw()).qa.password,'audit-only');});
 await test('Akun','Perangkat baru dapat login akun yang telah didaftarkan di perangkat lain',h=>{ok(h.call('ne','qa','audit-only'));},{loggedOut:true});
 await test('Akun','Akun baru mulai stok kosong',h=>{ok(h.call('H','fresh','audit-only'));h.call('ee','fresh');assert.equal(h.call('ae','fresh').products.length,0);});
 await test('Penyimpanan','JSON rusak tidak diam-diam menimpa database saat daftar',h=>{h.w.localStorage.setItem('dapur_users','{broken');h.call('H','newuser','audit-only');assert.equal(h.w.localStorage.getItem('dapur_users'),'{broken');});
 await test('Penyimpanan','Kegagalan simpan stok atomik',h=>{const before=h.raw();const native=h.w.Storage.prototype.setItem;h.w.Storage.prototype.setItem=function(){throw new h.w.DOMException('Quota exceeded','QuotaExceededError')};const r=h.call('Le','qa',product());assert.equal(typeof r,'string');h.w.Storage.prototype.setItem=native;assert.equal(h.raw(),before);return r;});
 await test('Penyimpanan','Registrasi gagal simpan memiliki error terkelola',h=>{h.w.Storage.prototype.setItem=function(){throw new h.w.DOMException('Quota exceeded','QuotaExceededError')};const r=h.call('H','fresh','audit-only');assert.equal(typeof r,'string');});
 // Dates vary with host timezone. Date-only fields must remain same calendar day.
 const priorTZ=process.env.TZ;
 for(const tz of ['UTC','Asia/Jakarta','America/Los_Angeles']){process.env.TZ=tz;
  await test('Tanggal','Label tanggal tetap 7 Okt di '+tz,h=>{assert.equal(h.call('C','2026-10-07'),'7 Okt 2026');});
  await test('Tanggal','Tanggal hari ini tidak terlewat di '+tz,h=>{assert.equal(h.call('S','2026-10-07'),'expiring');},{now:'2026-10-07T12:00:00Z'});
 }
 process.env.TZ=priorTZ;
 fs.writeFileSync(__dirname+'/domain-results.json',JSON.stringify({method:'isolated DOM + public store functions; dates frozen 7 Oct 2026',results},null,2));
 console.log(JSON.stringify({total:results.length,pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').map(({id,area,name,evidence})=>({id,area,name,evidence}))},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
