const {harness,base,product,recipe,activity,assert,fs,wait,text}=require('./harness.cjs');
const results=[];let n=0;
const ok=r=>assert.equal(r,null);
const like=async(h,s)=>{const e=h.all('button').find(e=>text(e).includes(s));assert(e,'No '+s);e.click();await wait()};
async function test(area,name,fn,opts={}){let h;try{h=harness(opts);await wait();const evidence=await fn(h);results.push({id:'E'+String(++n).padStart(3,'0'),area,name,status:'PASS',evidence:evidence||null,errors:h.errors});}catch(e){results.push({id:'E'+String(++n).padStart(3,'0'),area,name,status:'FAIL',evidence:e.message,dom:h?.dump(),errors:h?.errors});}finally{h?.close()}}
function sharedInit(map){return w=>{if(!map.size)for(let i=0;i<w.localStorage.length;i++){const k=w.localStorage.key(i);map.set(k,w.localStorage.getItem(k))}w.Storage.prototype.getItem=function(k){return map.get(String(k))??null};w.Storage.prototype.setItem=function(k,v){map.set(String(k),String(v))};w.Storage.prototype.removeItem=function(k){map.delete(String(k))}}}
const stocked=()=>({...base(),products:[product()],productArchive:{p1:product()},recipes:[recipe()]});
(async()=>{
 await test('Belanja gabungan','Receipt yang sudah habis dipakai tidak menutup kebutuhan baru',h=>{const a=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2},{itemId:'rice',quantity:100}]);const i=h.data().shoppingItems.find(i=>i.itemId==='egg');ok(h.call('vt','qa',i.id,product('x','egg',2)));ok(h.call('st','qa','r1',1));assert.equal(h.data().products.length,0);const p=h.call('lt','qa','r1',1,a.id,'meal-next');assert.equal(p.rows[0].additional,2,'Preview counts consumed purchase as coverage: '+JSON.stringify(p.rows[0]));},{data:{...base(),recipes:[recipe()]}});
 await test('Belanja gabungan','Receipt yang sudah melewati tanggal tidak menutup kebutuhan resep',h=>{const a=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2},{itemId:'rice',quantity:100}]);const i=h.data().shoppingItems.find(i=>i.itemId==='egg');ok(h.call('vt','qa',i.id,product('x','egg',2,{expiryDate:'2026-10-06'})));const p=h.call('lt','qa','r1',1,a.id,'meal-next');assert.equal(p.rows[0].additional,2,'Expired receipt treated as coverage: '+JSON.stringify(p.rows[0]));},{data:{...base(),recipes:[recipe()]}});
 await test('Belanja gabungan','Receipt tanggal belum diketahui dapat ditinjau dari rencana',h=>{const a=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2},{itemId:'rice',quantity:100}]);const i=h.data().shoppingItems.find(i=>i.itemId==='egg');ok(h.call('vt','qa',i.id,product('x','egg',2,{expiryDate:'',expiryKind:'unknown'})));const p=h.call('lt','qa','r1',1,a.id,'meal-next');assert.equal(p.rows[0].unverified,2,'Purchased unknown-expiry stock hidden from unverified count: '+JSON.stringify(p.rows[0]));},{data:{...base(),recipes:[recipe()]}});
 await test('Belanja gabungan','Preview UI sesudah receipt habis menawarkan beli ulang',async h=>{const a=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2},{itemId:'rice',quantity:100}]);const i=h.data().shoppingItems.find(i=>i.itemId==='egg');ok(h.call('vt','qa',i.id,product('x','egg',2)));ok(h.call('st','qa','r1',1));const ui=harness({data:h.data()});try{await wait();await ui.click('▣ Resep');await like(ui,'Menu r1');await ui.click('Rencanakan Bahan ke Belanja');const txt=text(ui.d.getElementById('root'));assert(txt.includes('Tambahan belanja: 2 buah'),'UI preview after consumed receipt: '+txt);return txt;}finally{ui.close()}},{data:{...base(),recipes:[recipe()]}});
 await test('Dua tab','Perubahan stok tab pertama memperbarui tampilan tab kedua',async h=>{const map=new Map(),first=harness({data:stocked(),before:sharedInit(map)}),second=harness({data:stocked(),before:sharedInit(map)});try{await wait();await second.click('▤ Inventori');ok(first.call('st','qa','r1',1));second.w.dispatchEvent(new second.w.StorageEvent('storage',{key:'dapur_users',newValue:map.get('dapur_users')}));await wait();assert.equal(second.data().products[0].quantity,8);assert(text(second.d.getElementById('root')).includes('Total tercatat: 8 buah'),'Second tab still shows '+text(second.d.getElementById('root')));}finally{first.close();second.close()}});
 await test('Dua tab','Logout tab pertama mengeluarkan tab kedua',async h=>{const map=new Map(),first=harness({data:stocked(),before:sharedInit(map)}),second=harness({data:stocked(),before:sharedInit(map)});try{await wait();first.call('re');second.w.dispatchEvent(new second.w.StorageEvent('storage',{key:'dapur_session',newValue:null}));await wait();assert(text(second.d.getElementById('root')).includes('Masuk'),'Second tab remains signed in after logout');}finally{first.close();second.close()}});
 await test('Dua tab','Edit metadata lama tidak menimpa perubahan tab lain tanpa konflik',h=>{const old=h.data().products[0];ok(h.call('Re','qa',{...old,expiryDate:'2026-10-20'}));const r=h.call('Re','qa',{...old,location:'Rak'});assert.equal(typeof r,'string','Stale edit accepted and changed expiry back to '+h.data().products[0].expiryDate);},{data:stocked()});
 await test('Dua tab','Jumlah stok terbaru tetap dijaga saat masak dari tampilan lama',h=>{ok(h.call('st','qa','r1',4));const before=h.raw(),r=h.call('st','qa','r1',2);assert.equal(typeof r,'string');assert.equal(h.raw(),before);assert.equal(h.data().products[0].quantity,2);},{data:stocked()});
 await test('Navigasi','Perubahan profil menampilkan nama terbaru di Beranda',async h=>{ok(h.call('W','qa','Nadia'));await h.click('Akun');await h.click('⌂ Beranda');assert(text(h.d.getElementById('root')).includes('Nadia'),'Home uses username instead of profile display name');});
 await test('Draf','Keluar aplikasi mencegah hilangnya draft resep',async h=>{await h.click('▣ Resep');await h.click('+ Buat Resep');await h.set(h.d.querySelector('input[placeholder="Contoh: Telur dadar"]'),'Makan malam');h.w.dispatchEvent(new h.w.Event('beforeunload',{cancelable:true}));assert(Object.keys(h.w.localStorage).some(k=>k.includes('draft')));});
 await test('Akun','Registrasi saat storage penuh tidak macet Memproses',async h=>{const errors=[];const onReject=e=>errors.push(e.message);process.on('unhandledRejection',onReject);try{await h.click('Daftar');await h.set(h.d.querySelector('input[type="text"]'),'fresh');await h.set(h.d.querySelector('input[type="password"]'),'audit-only');h.w.Storage.prototype.setItem=function(){throw new h.w.DOMException('Quota exceeded','QuotaExceededError')};h.d.querySelector('form').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));await wait(500);assert(!h.btn('Memproses...').disabled,'Registration remains disabled and unhandled errors: '+errors.join(','));}finally{process.off('unhandledRejection',onReject)}},{loggedOut:true});
 await test('Akun','Database JSON rusak menampilkan pemulihan, bukan kosong palsu',h=>{const txt=text(h.d.getElementById('root'));assert(/pulih|rusak|cadang|error/i.test(txt),'Corrupted database appears as empty kitchen: '+txt);},{usersRaw:'{bad-json'});
 await test('Inventori','Tanggal tersedia masa depan diblokir di UI',async h=>{await h.click('▤ Inventori');await h.click('+ Tambah');await h.set(h.field('Nama Produk *'),'egg');await h.set(h.field('Jumlah'),'2');await h.set(h.field('Tanggal stok tersedia'),'2026-10-08');h.d.querySelector('form').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));await wait();assert.equal(h.data().products.length,0);assert(text(h.d.getElementById('root')).includes('sebelumnya'))});
 await test('Resep','Pemeriksaan stok tanpa tanggal lewat UI dan verifikasi hanya per masakan',async h=>{await h.click('▣ Resep');await like(h,'Menu r1');assert(h.btn('Catat Masak · 1 porsi').disabled);await h.click('Periksa Stok Tanpa Tanggal');h.d.querySelector('input[type="checkbox"]').click();await wait();await h.click('Konfirmasi Pemeriksaan');assert(!h.btn('Catat Masak · 1 porsi').disabled);await h.click('Catat Masak · 1 porsi');await h.click('Simpan & Kurangi Stok');assert.equal(h.data().products[0].quantity,8);assert.equal(h.data().products[0].expiryDate,'');assert(h.btn('Catat Masak · 1 porsi').disabled);},{data:{...stocked(),products:[product('p1','egg',10,{expiryDate:'',expiryKind:'unknown'})]}});
 await test('Tanggal','Tanggal Jakarta tetap benar pada 00.30WIB',h=>{assert.equal(h.call('F'),'2026-10-07');assert.equal(h.call('C','2026-10-07'),'7 Okt 2026');assert.equal(h.call('S','2026-10-07'),'expiring');},{now:'2026-10-06T17:30:00Z'});
 await test('Tanggal','Tanggal Jakarta tetap benar pada 23.30WIB',h=>{assert.equal(h.call('F'),'2026-10-07');assert.equal(h.call('S','2026-10-07'),'expiring');},{now:'2026-10-07T16:30:00Z'});
 await test('Kuantitas','Koma desimal Indonesia dapat dimasukkan',async h=>{await h.click('▤ Inventori');await h.click('+ Tambah');await h.set(h.field('Nama Produk *'),'rice');await h.set(h.field('Jumlah'),'0,5');assert.equal(h.field('Jumlah').value,'0.5','Number input sanitizes 0,5 to '+JSON.stringify(h.field('Jumlah').value));});
 await test('Master','Rename master menjaga nama asli pada transaksi lama',h=>{const a=h.call('ft','qa','Mingguan',[{itemId:'egg',quantity:2}]);const i=h.data().shoppingItems[0];ok(h.call('vt','qa',i.id,product('x','egg',2)));ok(h.call('de','qa',{...h.data().itemMasters[0],name:'Telur Baru'},'egg'));assert.equal(h.data().products[0].name,'Telur Baru');assert.equal(h.data().shoppingItems[0].name,'Telur');return {currentStockName:h.data().products[0].name,historicalShoppingName:h.data().shoppingItems[0].name,note:'Historical name preserved intentionally; use stable item ID'};});
 await test('Inventori','Ketelitian desimal tidak membuat stok negatif setelah pemakaian berulang',h=>{for(let i=0;i<3;i++)ok(h.call('nt','qa',activity('a'+i,0.1)));assert.equal(h.data().products.length,0);assert.equal(h.data().productArchive.p1.quantity,0);},{data:{...base(),products:[product('p1','egg',0.3)]}});
 await test('Aktivitas','Pemakaian tidak sengaja dua kali pada event yang sama tidak tercatat ganda',async h=>{await h.click('✓ Aktivitas');await h.click('+ Catat Aktivitas');await like(h,'✅Dipakai');await h.set(h.d.querySelector('input[placeholder="mis. Masak malam, Sarapan..."]'),'Sarapan');await like(h,'Stok:');await h.set(h.field('Jumlah Telur (buah)'),'2');await h.click('Tambah ke Daftar');const b=h.btn('Simpan Pemakaian (1 batch)');b.click();b.click();await wait();assert.equal(h.data().products[0].quantity,8,'Same-tick double dispatch stock='+h.data().products[0].quantity);},{data:stocked()});
 await test('Belanja','Dua klik terpisah flush UI mencegah receipt ganda',async h=>{await h.click('◎ Belanja');await h.click('+ Tambah Belanja');await h.set(h.d.querySelector('input[placeholder="Contoh: Belanja Mingguan"]'),'Mingguan');await h.set(h.field('Nama Item *'),'egg');await h.set(h.field('Jumlah rencana *'),'5');await h.click('Simpan Belanja');await h.click('Catat pembelian Telur');await h.set(h.field('Jumlah yang dibeli (buah)'),'1');await h.set(h.field('Tanggal pada kemasan'),'2026-10-20');const b=h.btn('Simpan Pembelian & Stok');b.click();await wait();b.click();await wait();assert.equal(h.data().shoppingItems[0].receipts.length,1)});
 // Repeated stock ledger lifecycle, deterministic, no real data.
 await test('Ledger','100 siklus pakai/edit/hapus menjaga jumlah dan riwayat konsisten',h=>{for(let i=0;i<100;i++){const before=h.data().products[0].quantity;const a=activity('cycle'+i,0.25);ok(h.call('nt','qa',a));ok(h.call('et','qa',{...a,items:[{...a.items[0],quantity:0.5}]}));ok(h.call('tt','qa',a.id));assert.equal(h.data().products[0].quantity,before);assert(h.call('He','qa','p1').summary.consistent)}return {iterations:100,mutations:300,finalQuantity:h.data().products[0].quantity};},{data:stocked()});
 fs.writeFileSync(__dirname+'/edge-results.json',JSON.stringify({method:'isolated DOM, public store, two tab simulated shared storage; frozen dates',results},null,2));
 console.log(JSON.stringify({total:results.length,pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').map(({id,area,name,evidence})=>({id,area,name,evidence}))},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
