const {harness,base,product,recipe,activity,assert,fs,wait,text}=require('./harness.cjs');
const results=[];let n=0;const ok=r=>assert.equal(r,null);
const like=async(h,s)=>{const b=h.all('button').find(b=>text(b).includes(s));assert(b,'No '+s);b.click();await wait()};
const master=async h=>{await h.click('Akun');await like(h,'Data Master')};
const submit=async h=>{h.d.querySelector('form').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));await wait(400)};
async function test(area,name,fn,opts={}){const h=harness(opts);try{await wait();const evidence=await fn(h);results.push({id:'S'+String(++n).padStart(3,'0'),area,name,status:'PASS',evidence:evidence||null,errors:h.errors});}catch(e){results.push({id:'S'+String(++n).padStart(3,'0'),area,name,status:'FAIL',evidence:e.message,dom:h.dump(),errors:h.errors});}finally{h.close()}}
(async()=>{
 await test('Master UI','Kategori tambah/edit/hapus lewat UI',async h=>{await master(h);await h.click('+ Tambah');await h.set(h.d.querySelector('input'),'Baru');await h.click('Simpan');assert(h.data().categories.includes('Baru'));await h.click('Edit Baru');await h.set(h.d.querySelector('input'),'Baru2');await h.click('Simpan');assert(h.data().categories.includes('Baru2'));await h.click('Hapus Baru2');await h.click('Ya, hapus');assert(!h.data().categories.includes('Baru2'))});
 await test('Master UI','Kategori duplikat menampilkan error dan tetap berada di form',async h=>{await master(h);await h.click('+ Tambah');await h.set(h.d.querySelector('input'),'pokok');await h.click('Simpan');assert(h.d.querySelector('[role="alert"]'));assert.equal(h.data().categories.length,2)});
 await test('Master UI','Lokasi tambah/edit/hapus lewat UI',async h=>{await master(h);await h.click('Lokasi');await h.click('+ Tambah');await h.set(h.d.querySelector('input'),'Freezer');await h.click('Simpan');await h.click('Edit Freezer');await h.set(h.d.querySelector('input'),'Freezer atas');await h.click('Simpan');await h.click('Hapus Freezer atas');await h.click('Ya, hapus');assert(!h.data().locations.includes('Freezer atas'))});
 await test('Master UI','Master item baru dan konversi kemasan lewat UI',async h=>{await master(h);await h.click('Item');await h.click('+ Tambah');await h.set(h.field('Nama Item'),'Kopi');await h.set(h.field('Kategori'),'Pokok');await h.set(h.field('Satuan dasar'),'gram');await h.set(h.field('Satuan kemasan'),'bungkus');await h.set(h.field('Isi per kemasan'),'100');await h.set(h.field('Satuan isi kemasan'),'gram');await h.click('Simpan');const m=h.data().itemMasters.find(i=>i.name==='Kopi');assert.equal(m.packageSize,100);assert.equal(m.packageUnit,'bungkus')});
 await test('Akun UI','Ubah nama profil sukses',async h=>{await h.click('Akun');await like(h,'Pengaturan Profil');await h.set(h.d.querySelector('input[type="text"]'),'Nadia');await submit(h);assert.equal(JSON.parse(h.raw()).qa.profile.displayName,'Nadia');assert(text(h.d.getElementById('root')).includes('Nama berhasil disimpan'))});
 await test('Akun UI','Ubah nama kosong ditolak',async h=>{await h.click('Akun');await like(h,'Pengaturan Profil');await h.set(h.d.querySelector('input[type="text"]'),'');await submit(h);assert(text(h.d.getElementById('root')).includes('Nama tidak boleh kosong'))});
 for(const [label,old,next,confirm,error] of [['Password lama salah','wrong','new-pass','new-pass','saat ini salah'],['Password baru pendek','audit-only','x','x','minimal 6'],['Konfirmasi tidak cocok','audit-only','new-pass','different','tidak cocok'],['Password baru valid','audit-only','new-pass','new-pass',null]])await test('Akun UI',label,async h=>{await h.click('Akun');await like(h,'Ubah Kata Sandi');const a=h.all('input[type="password"]');await h.set(a[0],old);await h.set(a[1],next);await h.set(a[2],confirm);await submit(h);if(error){assert(text(h.d.getElementById('root')).includes(error));assert.equal(JSON.parse(h.raw()).qa.password,'audit-only')}else{assert.equal(JSON.parse(h.raw()).qa.password,'new-pass');assert(text(h.d.getElementById('root')).includes('berhasil diubah'))}});
 await test('Pembuangan','Buang dua batch atomik, lalu hapus aktivitas memulihkan keduanya',h=>{ok(h.call('it','qa',['p1','p2'],'Rusak','2026-10-07'));assert.equal(h.data().products.length,0);const id=h.data().activityLog[0].id;ok(h.call('tt','qa',id));assert.equal(h.data().products.length,2);assert.equal(h.data().products.reduce((a,p)=>a+p.quantity,0),15)},{data:{...base(),products:[product('p1','egg',10),product('p2','egg',5)]}});
 await test('Pembuangan','Batch hilang saat konfirmasi diblokir atomik',h=>{const raw=h.raw(),r=h.call('it','qa',['p1','missing'],'Rusak','2026-10-07');assert.equal(typeof r,'string');assert.equal(h.raw(),raw)},{data:{...base(),products:[product()]}});
 await test('Pembuangan','Jumlah batch berubah setelah dipilih tidak dibuang diam-diam',h=>{const selectedQuantity=h.data().products[0].quantity;ok(h.call('Ge','qa','p1',15,'Hitung tab lain'));const Old=h.w.Date;h.w.Date=class extends Old{constructor(...a){super(...(a.length?a:['2026-10-07T06:00:00Z']))}static now(){return new Old('2026-10-07T06:00:00Z').getTime()}};const r=h.call('it','qa',['p1'],'Buang semua pilihan','2026-10-07');assert.equal(typeof r,'string','Selected='+selectedQuantity+'; actual disposed='+h.data().activityLog[0].items[0].quantity);},{data:{...base(),products:[product()]}});
 fs.writeFileSync(__dirname+'/supplement-results.json',JSON.stringify({method:'isolated UI + batch disposal store',results},null,2));console.log(JSON.stringify({total:results.length,pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').map(({id,area,name,evidence})=>({id,area,name,evidence}))},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
